//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spherum.Mobile.Common.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Spherum.Mobile.Common.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        public static string OxfordCollege {
            get {
                return ResourceManager.GetString("OxfordCollege", resourceCulture);
            }
        }
        
        public static string CollegeAddress {
            get {
                return ResourceManager.GetString("CollegeAddress", resourceCulture);
            }
        }
        
        public static string StudentCard {
            get {
                return ResourceManager.GetString("StudentCard", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string MemberID {
            get {
                return ResourceManager.GetString("MemberID", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string StudentInformation {
            get {
                return ResourceManager.GetString("StudentInformation", resourceCulture);
            }
        }
        
        public static string StudentId {
            get {
                return ResourceManager.GetString("StudentId", resourceCulture);
            }
        }
        
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string AddNewStudent {
            get {
                return ResourceManager.GetString("AddNewStudent", resourceCulture);
            }
        }
        
        public static string StudentAddedMessage {
            get {
                return ResourceManager.GetString("StudentAddedMessage", resourceCulture);
            }
        }
        
        public static string FristNameErrorMessage {
            get {
                return ResourceManager.GetString("FristNameErrorMessage", resourceCulture);
            }
        }
        
        public static string LastNameErrorMessage {
            get {
                return ResourceManager.GetString("LastNameErrorMessage", resourceCulture);
            }
        }
        
        public static string NationalityErrorMessage {
            get {
                return ResourceManager.GetString("NationalityErrorMessage", resourceCulture);
            }
        }
        
        public static string StrreetAddressErrorrMessage {
            get {
                return ResourceManager.GetString("StrreetAddressErrorrMessage", resourceCulture);
            }
        }
        
        public static string CityErrorMessage {
            get {
                return ResourceManager.GetString("CityErrorMessage", resourceCulture);
            }
        }
        
        public static string StateErrorMessage {
            get {
                return ResourceManager.GetString("StateErrorMessage", resourceCulture);
            }
        }
        
        public static string CountryErrorMessage {
            get {
                return ResourceManager.GetString("CountryErrorMessage", resourceCulture);
            }
        }
        
        public static string ZipCodeErrorMessage {
            get {
                return ResourceManager.GetString("ZipCodeErrorMessage", resourceCulture);
            }
        }
        
        public static string EmailErrorMessage {
            get {
                return ResourceManager.GetString("EmailErrorMessage", resourceCulture);
            }
        }
        
        public static string PhoneErrorMessage {
            get {
                return ResourceManager.GetString("PhoneErrorMessage", resourceCulture);
            }
        }
        
        public static string NavigatingToStudentFormMessage {
            get {
                return ResourceManager.GetString("NavigatingToStudentFormMessage", resourceCulture);
            }
        }
        
        public static string NavigatingToStudentDetailsMessage {
            get {
                return ResourceManager.GetString("NavigatingToStudentDetailsMessage", resourceCulture);
            }
        }
        
        public static string GettingStudentsMessage {
            get {
                return ResourceManager.GetString("GettingStudentsMessage", resourceCulture);
            }
        }
    }
}
